In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('C:/Users/s/Desktop/금융빅데이터분석학/data/cars.csv', na_values=" ")

In [3]:
df

mpg   cylinders   cubicinches   hp   weightlbs   time-to-60   year  \
0    14.0           8         350.0  165      4209.0           12   1972   
1    31.9           4          89.0   71      1925.0           14   1980   
2    17.0           8         302.0  140      3449.0           11   1971   
3    15.0           8         400.0  150      3761.0           10   1971   
4    30.5           4          98.0   63      2051.0           17   1978   
..    ...         ...           ...  ...         ...          ...    ...   
256  17.0           8         305.0  130      3840.0           15   1980   
257  36.1           4          91.0   60      1800.0           16   1979   
258  22.0           6         232.0  112      2835.0           15   1983   
259  18.0           6         232.0  100      3288.0           16   1972   
260  22.0           6         250.0  105      3353.0           15   1977   

        brand  
0         US.  
1     Europe.  
2         US.  
3         US.  
4         US.  
..        ...  
256       US.  
257    Japan.  
258       US.  
259       US.  
260       US.  

[261 rows x 8 columns]

In [4]:
df.columns = ["mpg" , "cylinders" , "cubicinches" , "hp" , "weightlbs" , "time-to-60", "year" , "brand"]
df.head()

mpg  cylinders  cubicinches   hp  weightlbs  time-to-60  year     brand
0  14.0          8        350.0  165     4209.0          12  1972       US.
1  31.9          4         89.0   71     1925.0          14  1980   Europe.
2  17.0          8        302.0  140     3449.0          11  1971       US.
3  15.0          8        400.0  150     3761.0          10  1971       US.
4  30.5          4         98.0   63     2051.0          17  1978       US.

In [5]:
df.isnull().sum()

mpg            0
cylinders      0
cubicinches    2
hp             0
weightlbs      3
time-to-60     0
year           0
brand          0
dtype: int64

In [6]:
df["cubicinches"] = df["cubicinches"].replace(np.nan)
df["weightlbs"] = df["weightlbs"].replace(np.nan)

mean_cubicinches = df["cubicinches"].mean()
mean_weightlbs = df["weightlbs"].mean()

df["cubicinches"] = df["cubicinches"].replace(np.nan , mean_cubicinches)
df["weightlbs"] = df["weightlbs"].replace(np.nan , mean_weightlbs)

In [7]:
df["mpg"] = df["mpg"].astype("float32")

In [8]:
df['cubicinches'] = df['cubicinches'].astype('float32')
df['weightlbs'] = df['weightlbs'].astype('float32')

In [9]:
df['cylinders'] = df['cylinders'].astype('float32')
df['hp'] = df['hp'].astype('float32')
df['time-to-60'] = df['time-to-60'].astype('float32')
df['year'] = df['year'].astype('float32')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   mpg          261 non-null    float32
 1   cylinders    261 non-null    float32
 2   cubicinches  261 non-null    float32
 3   hp           261 non-null    float32
 4   weightlbs    261 non-null    float32
 5   time-to-60   261 non-null    float32
 6   year         261 non-null    float32
 7   brand        261 non-null    object 
dtypes: float32(7), object(1)
memory usage: 9.3+ KB


In [11]:
from sklearn.model_selection import train_test_split
df_train, df_test = train_test_split(df, test_size=0.1)

In [12]:
df_train

mpg  cylinders  cubicinches     hp  weightlbs  time-to-60    year  \
190  25.799999        4.0        156.0   92.0     2620.0        14.0  1982.0   
131  28.000000        4.0        151.0   90.0     2678.0        17.0  1981.0   
189  13.000000        8.0        440.0  215.0     4735.0        11.0  1974.0   
229  27.000000        4.0        140.0   86.0     2790.0        16.0  1983.0   
133  17.000000        8.0        304.0  150.0     3672.0        12.0  1973.0   
..         ...        ...          ...    ...        ...         ...     ...   
22   24.000000        6.0        200.0   81.0     3012.0        18.0  1977.0   
147  27.000000        4.0        151.0   90.0     2735.0        18.0  1983.0   
164  23.000000        4.0         97.0   54.0     2254.0        24.0  1973.0   
34   30.000000        4.0         97.0   67.0     1985.0        16.0  1978.0   
110  20.000000        4.0         97.0   88.0     2279.0        19.0  1974.0   

        brand  
190       US.  
131       US.  
189       US.  
229       US.  
133       US.  
..        ...  
22        US.  
147       US.  
164   Europe.  
34     Japan.  
110    Japan.  

[234 rows x 8 columns]

In [13]:
df_test.head()

mpg  cylinders  cubicinches     hp  weightlbs  time-to-60    year  \
138  22.000000        4.0        121.0   98.0     2945.0        15.0  1976.0   
167  26.000000        4.0        156.0   92.0     2585.0        15.0  1983.0   
16   31.799999        4.0         85.0   65.0     2020.0        19.0  1980.0   
54   16.500000        8.0        350.0  180.0     4380.0        12.0  1977.0   
196  27.200001        4.0        135.0   84.0     2490.0        16.0  1982.0   

        brand  
138   Europe.  
167       US.  
16     Japan.  
54        US.  
196       US.

In [14]:
X = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values
Y

array([' US.', ' Europe.', ' US.', ' US.', ' US.', ' US.', ' US.', ' US.',
       ' Europe.', ' Japan.', ' Japan.', ' Europe.', ' US.', ' US.',
       ' US.', ' US.', ' Japan.', ' US.', ' Japan.', ' Europe.',
       ' Japan.', ' Europe.', ' US.', ' US.', ' Japan.', ' Japan.',
       ' Japan.', ' US.', ' US.', ' US.', ' Japan.', ' US.', ' Japan.',
       ' US.', ' Japan.', ' US.', ' Europe.', ' Japan.', ' US.', ' US.',
       ' US.', ' US.', ' US.', ' US.', ' US.', ' Japan.', ' US.', ' US.',
       ' Europe.', ' US.', ' US.', ' Europe.', ' US.', ' Europe.', ' US.',
       ' US.', ' Japan.', ' US.', ' Europe.', ' US.', ' US.', ' Japan.',
       ' Japan.', ' Japan.', ' US.', ' US.', ' Europe.', ' Japan.',
       ' Europe.', ' US.', ' US.', ' US.', ' Japan.', ' Japan.',
       ' Europe.', ' US.', ' US.', ' Japan.', ' Europe.', ' Japan.',
       ' US.', ' US.', ' US.', ' Europe.', ' Europe.', ' Japan.', ' US.',
       ' US.', ' US.', ' US.', ' Japan.', ' Japan.', ' US.', ' US.',
       ' US

In [15]:
X = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
Y = encoder.fit_transform(Y)
print(Y)

[2 0 2 2 2 2 2 2 0 1 1 0 2 2 2 2 1 2 1 0 1 0 2 2 1 1 1 2 2 2 1 2 1 2 1 2 0
 1 2 2 2 2 2 2 2 1 2 2 0 2 2 0 2 0 2 2 1 2 0 2 2 1 1 1 2 2 0 1 0 2 2 2 1 1
 0 2 2 1 0 1 2 2 2 0 0 1 2 2 2 2 1 1 2 2 2 2 2 2 2 2 2 2 2 2 1 2 0 0 0 2 1
 0 2 1 0 2 2 2 2 2 0 0 2 2 0 2 2 2 0 2 0 2 2 2 2 2 2 2 0 0 2 1 1 1 2 0 2 2
 2 2 1 1 2 2 0 2 1 1 2 0 2 2 2 2 0 2 2 2 1 2 1 0 0 2 2 0 2 2 2 1 2 1 2 2 2
 2 2 2 2 2 2 2 2 2 2 0 2 0 0 1 0 2 2 2 2 2 1 2 2 1 1 2 1 0 2 1 1 2 2 2 2 0
 2 0 2 1 2 1 2 2 2 2 2 2 0 0 2 2 2 2 2 2 2 0 2 2 2 0 1 2 2 0 0 2 2 1 2 1 2
 2 2]


In [16]:
X_train = df[["mpg" , "cylinders" , "cubicinches" , "hp" , "weightlbs" , "time-to-60", "year"]].values
X_train = np.array(X_train, dtype = np.float32)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)

Y_train = Y
one_hot_dummy = tf.one_hot(Y, depth = 3).numpy()
Y_train = one_hot_dummy

print(X_train, 'shape = ', X_train.shape)
print(Y_train, 'shape = ', Y_train.shape)

[[0.10928962 1.         0.72868216 ... 0.76713943 0.23529413 0.08334351]
 [0.59836066 0.19999999 0.05426356 ... 0.09219858 0.3529412  0.75      ]
 [0.19125685 1.         0.60465115 ... 0.5425532  0.17647061 0.        ]
 ...
 [0.32786888 0.6        0.42377257 ... 0.36111107 0.4117647  1.        ]
 [0.21857926 0.6        0.42377257 ... 0.49497637 0.47058824 0.08334351]
 [0.32786888 0.6        0.47028422 ... 0.51418436 0.4117647  0.5       ]] shape =  (261, 7)
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.

In [17]:
tf.random.set_seed(2021)
W = tf.Variable(tf.random.normal([X_train.shape[1],Y_train.shape[1]], mean=0.0))
b = tf.Variable(tf.random.normal([Y_train.shape[1]], mean=0.0))
print('# Weights: \n', W.numpy(), '\n\n# Bias: \n', b.numpy())

# Weights: 
 [[ 1.0473857  -0.12665796  0.5701126 ]
 [-1.2995517   0.68507546 -0.6931981 ]
 [-0.14386335  0.86525923  1.4287399 ]
 [-0.8128876  -0.05127564 -0.14279948]
 [ 0.4418197   0.90691936 -1.2733945 ]
 [-0.580705   -0.20994303  0.11278591]
 [-0.3130786   1.4819225  -0.05825574]] 

# Bias: 
 [-0.5503563  1.0144334 -0.9311876]


In [18]:
def softmax(X):
    z = tf.matmul(X, W) + b
    sm = tf.nn.softmax(z)
    return sm

def cost_fn(Y_pred, Y_true):
    cost = tf.reduce_mean(-tf.reduce_sum(Y_true * tf.math.log(Y_pred), axis=1))
    return cost

learning_rate = 0.01
optimizer = tf.optimizers.SGD(learning_rate)

In [19]:
for step in range(10001):
        
    with tf.GradientTape() as g:
        pred = softmax(X_train)
        cost = cost_fn(pred, Y_train)
            
        gradients = g.gradient(cost, [W, b])
    
    optimizer.apply_gradients(zip(gradients,[W, b]))
    
    if step % 1000 == 0:
            
        print("step =", '%04d' % (step+1), "cost = {}, W = {}, b = {}".format(cost, W.numpy(), b.numpy()))

print('*'*50)
print(f'y = {W.numpy()}x + {b.numpy()}')

step = 0001 cost = 3.208346128463745, W = [[ 1.0481142  -0.12887421  0.5716004 ]
 [-1.2992141   0.6805305  -0.6889907 ]
 [-0.1437142   0.86211437  1.4317356 ]
 [-0.8126084  -0.05407478 -0.14027952]
 [ 0.44220152  0.9032983  -1.2701553 ]
 [-0.57987505 -0.2130944   0.11510732]
 [-0.3123974   1.4785184  -0.05553279]], b = [-0.54883426  1.0070225  -0.92529887]
step = 1001 cost = 0.7027245163917542, W = [[ 1.2786044  -0.18578692  0.3980224 ]
 [-1.3036566  -0.375356    0.3713381 ]
 [-0.19127896  0.06555468  2.27586   ]
 [-0.7661787  -0.6562162   0.41543186]
 [ 0.52578807  0.03540587 -0.48584932]
 [-0.28519937 -0.6240829   0.23141937]
 [-0.2022544   1.0461001   0.26674256]], b = [-0.09575102 -0.10057823 -0.27078125]
step = 2001 cost = 0.6534238457679749, W = [[ 1.3002557   0.03001484  0.16056976]
 [-1.3794594  -0.56426364  0.63604677]
 [-0.26820928 -0.12605196  2.5443976 ]
 [-0.7743912  -0.73192203  0.49935022]
 [ 0.5394602  -0.1626894  -0.30142567]
 [-0.2027405  -0.5841708   0.10904814]
 [-0

In [20]:
predicted = tf.argmax(softmax(X_train), axis = 1)
real      = tf.argmax(Y_train, axis = 1)

def accuracy(hypo, label):
    accuracyd = tf.reduce_mean(tf.cast(tf.equal(hypo, label), dtype=tf.float32))
    return accuracyd

acc = accuracy(predicted, real).numpy()
print("Accuracy: %s" % (acc*100))

Accuracy: 72.79693484306335


In [23]:
X_test = df_test[["mpg" , "cylinders" , "cubicinches" , "hp" , "weightlbs" , "time-to-60", "year"]].values
Y_test = df_test.iloc[:,-1].values

encoder = LabelEncoder()
Y_test = encoder.fit_transform(Y_test)

X_test = np.array(X_test, dtype = np.float32)
Y_test = np.array(Y_test, dtype = np.float32)

In [24]:
X_test.shape

(27, 7)

In [25]:
Y_test.shape

(27,)

In [27]:
Y_pred = softmax(X_test)
Y_pred = tf.argmax(Y_pred, axis=1)

In [28]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test, Y_pred))

0.5555555555555556
